# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83052c1da258fdbc294a8fd1fd3ca4b5f2a508e609eff1861eca3bbda2a2b616236ec8206a60639978b3276395f982bd25c871daa250c2d15bdfaac123804219

test:
  secret_key_base: 69818decf0caec455c8d523c457f0f123892dee1f0afa6a36bf904eddb5156bcf1442425876e771c1b19bf8611317c94c44e144b821268d951f2d655fe07d602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
